# Generated by Django 3.1.14 on 2024-07-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20240712_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='role',
            field=models.CharField(choices=[('CL', 'Client'), ('TH', 'Therapist')], default='CL', max_length=2),
        ),
    ]
