# Generated by Django 3.1.14 on 2024-07-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20240712_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='role',
            field=models.CharField(choices=[('CL', 'Client'), ('TH', 'Therapist')], max_length=2),
        ),
    ]
