# Generated by Django 3.1.14 on 2024-07-10 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('client', 'Client'), ('therapist', 'Therapist')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(choices=[('Occupational Therapist', 'Occupational Therapist'), ('Physiotherapist', 'Physiotherapist'), ('Speech Therapist', 'Speech Therapist'), ('Special Education Teacher', 'Special Education Teacher'), ('Psychologist', 'Psychologist'), ('Psychiatrist', 'Psychiatrist'), ('Counselor', 'Counselor'), ('Social Worker', 'Social Worker'), ('ABA Therapist', 'ABA Therapist'), ('Music Therapist', 'Music Therapist'), ('Art Therapist', 'Art Therapist'), ('Dance Therapist', 'Dance Therapist'), ('Recreational Therapist', 'Recreational Therapist'), ('Nutritionist', 'Nutritionist'), ('Other', 'Other')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('Celebral Palsy', 'Celebral Palsy'), ('Autism', 'Autism'), ('Down Syndrome', 'Down Syndrome'), ('ADHD', 'ADHD'), ('Hydrocephalus', 'Hydrocephalus'), ('Epilepsy', 'Epilepsy'), ('Developmental Delay', 'Developmental Delay'), ('Learning Disability', 'Learning Disability'), ('Intellectual Disability', 'Intellectual Disability'), ('Hearing Impairment', 'Hearing Impairment'), ('Visual Impairment', 'Visual Impairment'), ('Speech and Language Disorder', 'Speech and Language Disorder'), ('Physical Disability', 'Physical Disability'), ('Mental Health Disorder', 'Mental Health Disorder'), ('Multiple Disabilities', 'Multiple Disabilities'), ('Other', 'Other')], max_length=100)),
                ('age', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
